#!/usr/bin/env bash

mc_port=25566
#mc_port=80

webport=${1:-${PORT:-8080}}
#webport=${PORT}

#mc_port=${webport}

if [ -z "$NGROK_API_TOKEN" ]; then
  echo "You must set the NGROK_API_TOKEN config var to create a TCP tunnel!"
  exit 1
fi

# Start the TCP tunnel
ngrok_cmd="bin/ngrok tcp -authtoken $NGROK_API_TOKEN -log stdout --log-level debug ${NGROK_OPTS} ${mc_port}"
echo "Starting ngrok..."
eval "$ngrok_cmd | tee ngrok.log &"
ngrok_pid=$!

# Do an inline sync first, then start the background job
echo "Starting sync..."
bin/sync
if [ "$READ_ONLY" != "true" ]; then
  eval "while true; do sleep ${AWS_SYNC_INTERVAL:-300}; bin/sync; done &"
  sync_pid=$!
fi

# create server config
echo "server-port=${mc_port}" >> /app/server.properties
echo "server-ip=0.0.0.0" >> /app/server.properties
for f in whitelist banned-players banned-ips ops; do
  test ! -f $f.json && echo -n "[]" > $f.json
done

limit=$(ulimit -u)
case $limit in
  512)   # 2X Dyno
  heap=${MEMORY:-"768m"}
  ;;
  32768) # PX Dyno
  heap=${MEMORY:-"4g"}
  ;;
  *)     # 1X Dyno
  # Setting 1 = 384m
  # Setting 2 = 448m
  # Setting 3 = 500m
  heap=${MEMORY:-"500m"}
  ;;
esac

echo "Starting: minecraft ${mc_port}"
eval "screen -L -h 2048 -dmS minecraft java -Xmx${heap} -Xms${heap} -jar minecraft.jar nogui"
main_pid=$!

# Flush the logfile every second, and ensure that the logfile exists
screen -X "logfile 1" && sleep 1

echo "Tailing log"
eval "tail -f screenlog.0 &"
tail_pid=$!

trap "kill $ngrok_pid $main_pid $sync_pid $tail_pid" SIGTERM
trap "kill -9 $ngrok_pid $main_pid $sync_pid $tail_pid; exit" SIGKILL

#eval "ruby -rwebrick -e'WEBrick::HTTPServer.new(:BindAddress => \"0.0.0.0\", :Port => ${webport}, :MimeTypes => {\"rhtml\" => \"text/html\"}, :DocumentRoot => Dir.pwd).start'"

# DNS Update Section
if [ -n "$DYNU_CLIENT_ID" ]; then
	sleep 10 # Wait 10 Seconds First for Server to Start

	# Grab Full Ngrok Address
	ngrok_address=`cat ngrok.log`
	ngrok_address=${ngrok_address#*tcp://}
	ngrok_address=${ngrok_address%% *}

	# Grab Ngrok IP and Port
	ngrok_ip=`echo $ngrok_address | cut -d ':' -f 1`
	ngrok_ip=`dig +short ${ngrok_ip}`
	ngrok_port=`echo $ngrok_address | cut -d ':' -f 2`

	# Cleanup
	unset ngrok_address

	# Retrieve Dynu Keys
	dynu_client_id=${DYNU_CLIENT_ID}
	dynu_secret=${DYNU_SECRET}
	dynu_full="${dynu_client_id}:${dynu_secret}"

	# Cleanup
	unset dynu_client_id
	unset dynu_secret

	# Retrieve Dynu Token
	dynu_token=`curl --silent -X GET https://api.dynu.com/v2/oauth2/token -H "accept: application/json" -u "${dynu_full}"`
	dynu_token=`echo $dynu_token | cut -d \" -f 4`

	# Cleanup
	unset dynu_full

	# Get Domain Name + ID
	domain=`curl --silent -X GET "https://api.dynu.com/v2/dns" -H "accept: application/json" -H "Authorization: Bearer ${dynu_token}"`
	domain_id=`echo $domain | cut -d \" -f 7`
	domain_id=${domain_id:1:-1}
	domain=`echo $domain | cut -d \" -f 10`

	# Get DNS Records of Domain ID
	dnses=`curl --silent -X GET "https://api.dynu.com/v2/dns/${domain_id}/record" -H "accept: application/json" -H "Authorization: Bearer ${dynu_token}"`
	dnses=${dnses#*id}
	dnses=${dnses#*id}
	dnses_ip=${dnses%%,*}
	dnses_ip=${dnses_ip:2}
	dnses=${dnses#*id}
	dnses_port=${dnses%%,*}
	dnses_port=${dnses_port:2}
	
	# Cleanup
	unset dnses
	
	# Update DNS for Ngrok IP
	curl --silent -X POST "https://api.dynu.com/v2/dns/${domain_id}/record/${dnses_ip}" -H "accept: application/json" -H "Authorization: Bearer ${dynu_token}" -H "Content-Type: application/json" -d "{\"nodeName\":\"mcngrok\",\"recordType\":\"A\",\"ttl\":120,\"state\":true,\"group\":\"\",\"ipv4Address\":\"${ngrok_ip}\"}"
	
	# Update DNS for Ngrok PORT
	curl --silent -X POST "https://api.dynu.com/v2/dns/${domain_id}/record/${dnses_port}" -H "accept: application/json" -H "Authorization: Bearer ${dynu_token}" -H "Content-Type: application/json" -d "{\"nodeName\":\"_minecraft._tcp\",\"recordType\":\"SRV\",\"ttl\":120,\"state\":true,\"group\":\"\",\"host\":\"mcngrok.${domain}\",\"priority\":10,\"weight\":5,\"port\":${ngrok_port}}"
	
	# Cleanup
	unset dynu_token
	unset domain_id
	unset dnses_ip
	unset dnses_port
	unset ngrok_ip
	unset ngrok_port
	
	echo -e "Finished DNS Update! \nConnect to your Server Now at '$domain'"
	
	# Cleanup
	unset domain
fi
# DNS Update Section

# Application Exits unless we Loop Forever here
while :; do
    sleep 10
done