#!/usr/bin/env bash

perform_save=${SYNC_SAVE:-"true"}
perform_load=${SYNC_LOAD:-"true"}

echo "Syncing..."

# Amazon S3 Sync
if [ -n "$AWS_BUCKET" ]; then
  cat << EOF > .s3cfg
[default]
access_key = ${AWS_ACCESS_KEY}
secret_key = ${AWS_SECRET_KEY}
EOF
  if [ -d world ]; then
	if [ "$perform_save" = "true" ]; then
		s3cmd sync world/ s3://${AWS_BUCKET}/world/
		screen -S minecraft -p 0 -X stuff "say §aWorld Saved^M"
	fi
  else
	if [ "$perform_load" = "true" ]; then
		mkdir -p world
		cd world
		s3cmd get --recursive s3://${AWS_BUCKET}/world/
		cd ..
	fi
  fi
  rm .s3cfg
fi

# Dropbox Sync
if [ -n "$DROPBOX_ACCESS_TOKEN" ]; then
  cat << EOF > .dropbox_uploader
CONFIGFILE_VERSION=2.0
OAUTH_APP_KEY=${DROPBOX_APP_KEY}
OAUTH_APP_SECRET=${DROPBOX_APP_SECRET}
OAUTH_REFRESH_TOKEN=${DROPBOX_ACCESS_TOKEN}
EOF
  if [ -d world ]; then
	if [ "$perform_save" = "true" ]; then
		tar -czvf backup.tar.gz world world_nether world_the_end plugins mods
		bin/dropbox_uploader.sh upload backup.tar.gz /
		rm backup.tar.gz
		screen -S minecraft -p 0 -X stuff "say §aWorld Saved^M"
	fi
  else
	if [ "$perform_load" = "true" ]; then
		if bin/dropbox_uploader.sh download /backup.tar.gz
		then
		  tar -xzvf backup.tar.gz
		  rm backup.tar.gz
		fi
	fi
  fi
  rm .dropbox_uploader
fi